name: icon_font
version: 0.0.1
description: >-
  Converts SVG icons to OTF font and generates Flutter-compatible class.
  Provides an API and a CLI tool.
homepage: https://github.com/SkinnyMind/icon_font
environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  args: ^2.6.0
  collection: ^1.19.0
  dart_style: ^3.0.1
  logger: ^2.5.0
  meta: ^1.15.0
  path: ^1.9.0
  path_parsing: ^1.1.0
  pub_semver: ^2.1.5
  vector_math: ^2.1.4
  xml: ^6.5.0
  yaml: ^3.1.3

dev_dependencies:
  custom_lints:
    git: https://github.com/SkinnyMind/custom_lints
  test: ^1.25.14

executables:
  generate: generate
